#!/usr/bin/env php
<?php

// locate .git folders under CWD
exec("find . -iname .git", $response);
$currentDir = getcwd();

foreach($response as $line) {
	$line = trim($line);
	if (!file_exists($line))
		continue;

	if (!is_dir($line))
		continue;

	$rel = substr(realpath($line), strlen($currentDir) + 1);
	$rel = dirname($rel);
	echo $rel."\n";
}