#!/usr/bin/env php
<?php

// this is not actually used at all (as I'm not currently using these on a server the has repo's
$opts = getopt('v:');
if (!isset($opts['v'])) {
    echo "Current Tags:\n";
    exec("git tag", $output);
    foreach($output as $line) {
        echo "\t".trim($line)."\n";
    }

    echo "\n";
    echo "SemVer: Major = Backwards Incompatible, Minor = Backwards compatible new features, Revision = Bug fixes\n";
	echo "Enter version:";
	$opts['v'] = trim(fgets(STDIN));
}

// validate version
$version = $opts['v'];
if (substr($version, 0, 1) == 'v'){
    $version = trim(substr($version, 1));
}
$parts = explode('.', $version);
if (count($parts) > 3) {
    echo "Invalid version format x.y.z\n";
    exit;
}

foreach($parts as $part) {
    if (!is_numeric($part)) {
        echo "Invalid version format x.y.z\n";
        exit;
    }
}

exec("git tag -a v".$version." -m\"version ".$version."\"");
exec("git push origin v".$version);