#!/usr/bin/env php
<?php

use Danny\Scripts\Composer\Packagist;

$vendorPath = __DIR__;
while(!file_exists($vendorPath.DIRECTORY_SEPARATOR.'vendor') && strlen($vendorPath) > 0) {
	$vendorPath = dirname($vendorPath);
}
require $vendorPath.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

$script = array_shift($argv);
$search_terms = array_shift($argv);

$packagist = new Packagist();
$packagist->getProviders();
$results = $packagist->search('', $search_terms);
echo "Favs\t\tDownloads\tPackage\n";
foreach($results as $result) {
    $favourites = str_pad($result->getFavourites(), 10, ' ', STR_PAD_LEFT);
    $downloads = str_pad($result->getDownloads(), 10, ' ', STR_PAD_LEFT);

    echo $favourites."\t".$downloads."\t".$result->getName()."\n";
    if ($result->getAbandoned()) {
        echo "\tsuperceded by ".$result->getAbandoned()."\n";
    }
}