#!/usr/bin/env php
<?php

$options = getopt('', [
    'user:',
    'host:',
    'database:',
    'old-prefix:',
    'new-prefix:',
]);

$user = $options['user'] ?? 'root';
$host = $options['host'] ?? 'localhost';
$db   = $options['database'] ?? '';

if (!isset($options['old-prefix']) && !isset($options['new-prefix'])) {
    echo "Must specify AT LEAST one of old-prefix / new-prefix\n";
    exit;
}

exec("stty -echo");
echo "Password for {$user}:";
$password = trim(fgets(STDIN));
exec("stty echo");
echo "\n";

if ($db === '') {
    echo "Enter database name:";
    $db = trim(fgets(STDIN));
}

$database = new PDO("mysql:host=$host", $user, $password);
$query = $database->query("SHOW TABLES IN `$db`");
if ($query === false) {
    echo "Database doesn't exist\n";
    exit;
}

$tables = [];
while($row = $query->fetch(PDO::FETCH_NUM)) {
    $old_table = $row[0];
    $new_table = $row[0];
    if (isset($options['old-prefix'])) {
        if (substr($new_table, 0, strlen($options['old-prefix'])) !== $options['old-prefix'])
            continue;
        $new_table = substr($new_table, strlen($options['old-prefix']));
    }

    if (isset($options['new-prefix'])) {
        $new_table = $options['new-prefix'].$new_table;
    }

    if ($new_table === $old_table || $new_table === '') {
        echo "Unable to rename ".$old_table."\n";
        continue;
    }

    $database->exec("RENAME `$db`.`$old_table` TO `$db`.`$new_table`");
}
