#!/usr/bin/env bash

if [ ! -d ~/bin/app-installer ]; then
    git clone git@ogg.cain.mobi:apps/installer.git ~/bin/app-installer
    composer install --no-dev -d ~/bin/app-installer
fi

if [ ! -f ~/bin/app-installer/.env ]; then
    echo "Configure .env file in ~bin/app-installer"
    exit 1
fi

php8.1 ~/bin/app-installer/scripts/install.php "$@"
