#!/usr/bin/env php
<?php

$dir = getcwd();
$file = $dir.DIRECTORY_SEPARATOR.'composer.json';
if (file_exists($file)) {
	$config = file_get_contents($file);
	$config = json_decode($file, true);
} else {
	$config = [
		'name' => 'danny.cain/scripts-install'
	];
}

if (!isset($config['repositories'])) {
	$config['repositories'] = [];
}
if (!isset($config['require'])) {
	$config['require'] = [];
}

$config['require']['danny.cain/scripts'] = 'dev-master';
$config['require']['danny.cain/dpress-core'] = 'dev-master';
$config['require']['danny.cain/dpress-generic'] = 'dev-master';
$config['require']['danny.cain/crypto'] = '~0.1';
$config['require']['danny.cain/datalayer'] = '^1.0';
$config['require']['danny.cain/introspect'] = '^0.3';
$config['require']['danny.cain/dependencies'] = '^1.0';
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:danny/scripts.git'];
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:dpress/core.git'];
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:dpress-generic/generic.git'];
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:lib/crypto.git'];
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:lib/datalayer.git'];
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:lib/introspect.git'];
$config['repositories'][] = [ 'type' => 'git', 'url' => 'gitea@rincewind.dannycain.com:lib/dependencies.git'];

file_put_contents($file, json_encode($config, JSON_PRETTY_PRINT));
exec("composer update");